https://github.com/mrdbourke/zero-to-mastery-ml/blob/master/section-2-data-science-and-ml-tools/numpy-exercises.ipynb

In [1]:
import numpy as np

In [2]:
one_dim_array = np.array([1, 2, 3])
one_dim_array.shape

two_dim_array = np.array([[1, 2, 3], 
                        [4, 5, 6]])

three_dim_array = np.ones((3,3))
three_dim_array, two_dim_array.shape, type(three_dim_array)

(array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]),
 (2, 3),
 numpy.ndarray)

In [3]:
def print_array_info(array):
    print("Shape:", array.shape)
    print("Data type:", array.dtype)
    print("Type:", type(array))
    print("Number of dimensions:", array.ndim)
    print("Size:", array.size)
    print("-" * 40)

print_array_info(one_dim_array)
print_array_info(two_dim_array)
print_array_info(three_dim_array)


Shape: (3,)
Data type: int64
Type: <class 'numpy.ndarray'>
Number of dimensions: 1
Size: 3
----------------------------------------
Shape: (2, 3)
Data type: int64
Type: <class 'numpy.ndarray'>
Number of dimensions: 2
Size: 6
----------------------------------------
Shape: (3, 3)
Data type: float64
Type: <class 'numpy.ndarray'>
Number of dimensions: 2
Size: 9
----------------------------------------


In [4]:
import pandas as pd

In [5]:
data_frame = pd.DataFrame(three_dim_array)
data_frame

0    1    2
0  1.0  1.0  1.0
1  1.0  1.0  1.0
2  1.0  1.0  1.0

In [6]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10,2)) 
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [7]:
# Create an array of shape (7, 2, 3) of only zeros
zeroes = np.zeros((7, 2, 3))
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [8]:
# Create an array within a range of 0 and 100 with step 3
ranged = np.arange(0, 100, 3)
ranged

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [9]:
# Create a random array with numbers between 0 and 10 of size (7, 2)

randomized = np.random.randint(0, 10, size=(7,2))
randomized

array([[9, 9],
       [4, 3],
       [4, 6],
       [9, 1],
       [4, 6],
       [4, 8],
       [9, 7]])

In [10]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_fl = np.random.random((7,2))
random_fl

array([[0.12509824, 0.24284935],
       [0.84309929, 0.67673679],
       [0.07024933, 0.16972169],
       [0.86936332, 0.0569105 ],
       [0.94917098, 0.24109992],
       [0.98654725, 0.56473299],
       [0.53591571, 0.31876108]])

In [11]:
# Set the random seed to 42
np.random.seed(seed=42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
randomized = np.random.randint(0, 10, size=(4, 6))
randomized

# The output of this array will always be the same, because setting random seed gives the opportunity for reproducible results.

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [12]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
randomized2 = np.random.randint(1, 10, size=(3, 7))

# Find the unique numbers in the array you just created
print("Array created:", randomized2)
print("Unique numbers:", np.unique(randomized2))

Array created: [[9 1 3 7 4 9 3]
 [5 3 7 5 9 7 2]
 [4 9 2 9 5 2 4]]
Unique numbers: [1 2 3 4 5 7 9]


In [13]:
# Find the 0'th index of the latest array you created
print("0th index:", randomized2[0])

0th index: [9 1 3 7 4 9 3]


In [14]:
# Get the first 2 rows of latest array you created
# a fancy output
df = pd.DataFrame(randomized2[:2])

print("First 2 rows:")
display(df)

First 2 rows:


0  1  2  3  4  5  6
0  9  1  3  7  4  9  3
1  5  3  7  5  9  7  2

In [15]:
# Get the first 2 values of the first 2 rows of the latest array
df = pd.DataFrame(randomized2[:2, :2])

print("First 2 values of the first 2 rows:")
display(df)

First 2 values of the first 2 rows:


0  1
0  9  1
1  5  3

In [16]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables

first_array = np.random.randint(0, 10, size=(3,5))
second_array = np.ones((3,5))

In [17]:
# Add the two arrays together
sum1 = pd.DataFrame(first_array + second_array)

print("first_array + second_array:")
display(sum1)
print("-" * 24)

first_array + second_array:


0     1    2    3    4
0  7.0   8.0  3.0  1.0  4.0
1  2.0   8.0  4.0  2.0  6.0
2  6.0  10.0  4.0  6.0  2.0

------------------------


In [18]:
# Create another array of ones of shape (5, 3)
third_array = np.ones((5, 3))

# Try add the array of ones and the other most recent array together
# transposing the third array so it can be added

third_array = np.ones((5, 3)).T
sum2 = pd.DataFrame(second_array + third_array)

print("second_array + third_array:")
display(sum2)
print("-" * 24)

second_array + third_array:


0    1    2    3    4
0  2.0  2.0  2.0  2.0  2.0
1  2.0  2.0  2.0  2.0  2.0
2  2.0  2.0  2.0  2.0  2.0

------------------------


In [19]:
# Create another array of ones of shape (3, 5)
fourth_array = np.ones((3, 5))

In [20]:
# Subtract the new array of ones from the other most recent array
diff = pd.DataFrame(third_array - fourth_array)

print("third_array - fourth_array:")
display(diff)
print("-" * 24)

third_array - fourth_array:


0    1    2    3    4
0  0.0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0  0.0

------------------------


In [21]:
# Multiply the ones array with the latest array
mult = pd.DataFrame(third_array * fourth_array)

print("third_array * fourth_array:")
display(mult)
print("-" * 24)

third_array * fourth_array:


0    1    2    3    4
0  1.0  1.0  1.0  1.0  1.0
1  1.0  1.0  1.0  1.0  1.0
2  1.0  1.0  1.0  1.0  1.0

------------------------


In [22]:
# Take the latest array to the power of 2 using '**'
third_array ** 2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
# Do the same thing with np.square()
np.square(third_array)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [24]:
# Find the mean of the latest array using np.mean()
np.mean(third_array)

1.0

In [25]:
# Find the maximum of the latest array using np.max()
np.max(third_array)

1.0

In [26]:
# Find the minimum of the latest array using np.min()
np.min(third_array)

1.0

In [27]:
# Find the standard deviation of the latest array
np.std(third_array)

0.0

In [28]:
# Find the variance of the latest array
np.var(third_array)

0.0

In [29]:
# Reshape the latest array to (3,5,1)
third_array.reshape(3,5,1)

array([[[1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.]]])

In [30]:
# Transpose the latest array
third_array_transposed = third_array.T
third_array_transposed

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])